export const decoracoes = [
  {
    nome: 'Vasos decorativos',
    altura: 450,
    largura: 678,
    descricao: 'Vasos feitos de cimento, estilo pessoas com a planta na cabeça',
    url: 'images/dec1.jpeg',
  },
  {
    nome: 'Luminária de Madeira',
    altura: 800,
    largura: 800,
    descricao: 'Luminária feitas de madeira de bambu',
    url: 'images/dec2.jpeg',
  },
  {
    nome: 'Vasos decorativos',
    altura: 450,
    largura: 678,
    descricao: 'Vasos feitos de cimento, estilo pessoas com a planta na cabeça',
    url: 'images/dec1.jpeg',
  },
  {
    nome: 'Luminária de Madeira',
    altura: 800,
    largura: 800,
    descricao: 'Luminária feitas de madeira de bambu',
    url: 'images/dec2.jpeg',
  },
  {
    nome: 'Vasos decorativos',
    altura: 450,
    largura: 678,
    descricao: 'Vasos feitos de cimento, estilo pessoas com a planta na cabeça',
    url: 'images/dec1.jpeg',
  },
  {
    nome: 'Luminária de Madeira',
    altura: 800,
    largura: 800,
    descricao: 'Luminária feitas de madeira de bambu',
    url: 'images/dec2.jpeg',
  },
  {
    nome: 'Vasos decorativos',
    altura: 450,
    largura: 678,
    descricao: 'Vasos feitos de cimento, estilo pessoas com a planta na cabeça',
    url: 'images/dec1.jpeg',
  },
  {
    nome: 'Luminária de Madeira',
    altura: 800,
    largura: 800,
    descricao: 'Luminária feitas de madeira de bambu',
    url: 'images/dec2.jpeg',
  },
  {
    nome: 'Vasos decorativos',
    altura: 450,
    largura: 678,
    descricao: 'Vasos feitos de cimento, estilo pessoas com a planta na cabeça',
    url: 'images/dec1.jpeg',
  },
  {
    nome: 'Luminária de Madeira',
    altura: 800,
    largura: 800,
    descricao: 'Luminária feitas de madeira de bambu',
    url: 'images/dec2.jpeg',
  },
  {
    nome: 'Vasos decorativos',
    altura: 450,
    largura: 678,
    descricao: 'Vasos feitos de cimento, estilo pessoas com a planta na cabeça',
    url: 'images/dec1.jpeg',
  },
  {
    nome: 'Luminária de Madeira',
    altura: 800,
    largura: 800,
    descricao: 'Luminária feitas de madeira de bambu',
    url: 'images/dec2.jpeg',
  },
  {
    nome: 'Vasos decorativos',
    altura: 450,
    largura: 678,
    descricao: 'Vasos feitos de cimento, estilo pessoas com a planta na cabeça',
    url: 'images/dec1.jpeg',
  },
  {
    nome: 'Luminária de Madeira',
    altura: 800,
    largura: 800,
    descricao: 'Luminária feitas de madeira de bambu',
    url: 'images/dec2.jpeg',
  },
  {
    nome: 'Vasos decorativos',
    altura: 450,
    largura: 678,
    descricao: 'Vasos feitos de cimento, estilo pessoas com a planta na cabeça',
    url: 'images/dec1.jpeg',
  },
  {
    nome: 'Luminária de Madeira',
    altura: 800,
    largura: 800,
    descricao: 'Luminária feitas de madeira de bambu',
    url: 'images/dec2.jpeg',
  },
  {
    nome: 'Vasos decorativos',
    altura: 450,
    largura: 678,
    descricao: 'Vasos feitos de cimento, estilo pessoas com a planta na cabeça',
    url: 'images/dec1.jpeg',
  },
  {
    nome: 'Luminária de Madeira',
    altura: 800,
    largura: 800,
    descricao: 'Luminária feitas de madeira de bambu',
    url: 'images/dec2.jpeg',
  },
];
