export const pinturas = [
  {
    nome: 'Pintura velha guarda',
    altura: 480,
    largura: 360,
    descricao: 'Pintura de um casal de senhores dentro da aguá, feita de tinta a óleo',
    url: 'images/art1.jpeg',
  },
  {
    nome: 'Pintura jovens',
    altura: 540,
    largura: 960,
    descricao: 'Pintura de jovens na arte, musica e mídia',
    url: 'images/art2.jpeg',
  },
  {
    nome: 'Mural de madeira',
    altura: 1691,
    largura: 1689,
    descricao: 'Mural de madeira lalalalaal',
    url: 'images/art3.jpeg',
  },
  {
    nome: 'Pintura velha guarda',
    altura: 480,
    largura: 360,
    descricao: 'Pintura de um casal de senhores dentro da aguá, feita de tinta a óleo',
    url: 'images/art1.jpeg',
  },
  {
    nome: 'Pintura jovens',
    altura: 540,
    largura: 960,
    descricao: 'Pintura de jovens na arte, musica e mídia',
    url: 'images/art2.jpeg',
  },
  {
    nome: 'Mural de madeira',
    altura: 1691,
    largura: 1689,
    descricao: 'Mural de madeira lalalalaal',
    url: 'images/art3.jpeg',
  },
  {
    nome: 'Pintura velha guarda',
    altura: 480,
    largura: 360,
    descricao: 'Pintura de um casal de senhores dentro da aguá, feita de tinta a óleo',
    url: 'images/art1.jpeg',
  },
  {
    nome: 'Pintura jovens',
    altura: 540,
    largura: 960,
    descricao: 'Pintura de jovens na arte, musica e mídia',
    url: 'images/art2.jpeg',
  },
  {
    nome: 'Mural de madeira',
    altura: 1691,
    largura: 1689,
    descricao: 'Mural de madeira lalalalaal',
    url: 'images/art3.jpeg',
  },
  {
    nome: 'Pintura velha guarda',
    altura: 480,
    largura: 360,
    descricao: 'Pintura de um casal de senhores dentro da aguá, feita de tinta a óleo',
    url: 'images/art1.jpeg',
  },
  {
    nome: 'Pintura jovens',
    altura: 540,
    largura: 960,
    descricao: 'Pintura de jovens na arte, musica e mídia',
    url: 'images/art2.jpeg',
  },
  {
    nome: 'Mural de madeira',
    altura: 1691,
    largura: 1689,
    descricao: 'Mural de madeira lalalalaal',
    url: 'images/art3.jpeg',
  },
];
